package dev.abelab.rdid.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.name
     *
     * @mbg.generated
     */
    private String name;
}