package dev.abelab.rdid.db.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.client_id
     *
     * @mbg.generated
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.expired_in
     *
     * @mbg.generated
     */
    private Integer expiredIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;
}