package dev.abelab.rdid.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UserGroupMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group_member.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group_member.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;
}