spring:
  datasource:
    url:
    username:
    password:
    driver:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver: ${spring.datasource.driver}
    locations: classpath:db/migration
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Tokyo

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

project:
  name: rdid
  version: 1.0_SNAPSHOP
  package: dev.abelab.rdid
  mybatis:
    config:
      file: generatorConfig.xml
    model:
      package: db.entity
    client:
      package: db.mapper.base
      type: XMLMAPPER
    map:
      package: db.mapper.base
  swagger:
    protocol: http
    hostname: localhost:${server.port}
  admin-account:
    first-name: 健太朗
    last-name: 阿部
    email: admin@abelab.dev
    password: FK2$XGYwrWfyNNxS
    admission-year: 2019

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/base/*Mapper.xml
    - classpath:/db/mapper/*Mapper.xml

jwt:
  secret: sGjYaViPIHkqnItJt2ST4XpQEbEMpjgmC7WenZVd0LeeGgxMyE2/d0U+sDKULGHV2QWkGxuIGPcVvW7+6mxpjmlEf7jNgBs3dhxd5IkNsTjDMeenMMWZIpayKr/OADG8NmSK/eIZ3Cr6pVxVFSfro3GBRV2ySMZ09wk4Ip8UaPy3dho07AnJdinTXzWE3it1OsHkzm5pdrHQuF4RH18OFiAQuSPk6+yVj4EezA==
  issuer: rdid.abelab.dev
  timeout: 604800

logging:
  level:
    root: INFO
