spring:
  datasource:
    url: jdbc:mysql://localhost:3307/rdid?useSSL=false&allowPublicKeyRetrieval=true
    username: rdid
    password: rdid
    driver: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: ERROR
