spring:
  datasource:
    url:
    username:
    password:
    driver:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver: ${spring.datasource.driver}
    locations: classpath:db/migration
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Tokyo

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

project:
  name: rdid
  version: 1.0_SNAPSHOP
  package: dev.abelab.rdid
  mybatis:
    config:
      file: generatorConfig.xml
    model:
      package: db.entity
    client:
      package: db.mapper.base
      type: XMLMAPPER
    map:
      package: db.mapper.base
  swagger:
    protocol: http
    hostname: localhost:${server.port}

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/base/*Mapper.xml
    - classpath:/db/mapper/*Mapper.xml

jwt:
  secret: yjA4Q3jHenlf3hp25eHMhw==
  issuer: rdid.abelab.dev
  timeout: 604800

logging:
  level:
    root: INFO
