package dev.abelab.rdid.db.mapper.base;

import dev.abelab.rdid.db.entity.UserGroupRole;
import dev.abelab.rdid.db.entity.UserGroupRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserGroupRoleBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    long countByExample(UserGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int deleteByExample(UserGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("groupId") Integer groupId, @Param("clientId") Integer clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int insert(UserGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int insertSelective(UserGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    List<UserGroupRole> selectByExample(UserGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    UserGroupRole selectByPrimaryKey(@Param("groupId") Integer groupId, @Param("clientId") Integer clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserGroupRole record, @Param("example") UserGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserGroupRole record, @Param("example") UserGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGroupRole record);
}