package dev.abelab.rdid.db.mapper.base;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import dev.abelab.rdid.db.entity.UserGroupMember;
import dev.abelab.rdid.db.entity.UserGroupMemberExample;

@Mapper
public interface UserGroupMemberBaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_group_member
     *
     * @mbg.generated
     */
    long countByExample(UserGroupMemberExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_group_member
     *
     * @mbg.generated
     */
    int deleteByExample(UserGroupMemberExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_group_member
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("groupId") Integer groupId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_group_member
   *
   * @mbg.generated
   */
  int insert(UserGroupMember record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_group_member
   *
   * @mbg.generated
   */
  int insertSelective(UserGroupMember record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_group_member
   *
   * @mbg.generated
   */
  List<UserGroupMember> selectByExample(UserGroupMemberExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_group_member
   *
   * @mbg.generated
   */
  int updateByExampleSelective(@Param("record") UserGroupMember record, @Param("example") UserGroupMemberExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_group_member
   *
   * @mbg.generated
   */
  int updateByExample(@Param("record") UserGroupMember record, @Param("example") UserGroupMemberExample example);
}